I/O revision II 文本提取补充实现
MewX/cross-channel_chinesizing_project pull request #3
Opened 2019-04-19 12:53 UTC by ddddyyyy

文本的结尾判断并没有加边界检测，会将三个资源文件的一小部分误提取，不过好像影响不大，就不管了

2019-04-19 14:02 UTC, MewX requested changes
main函数的改动不用提交，然后主要改动好像全都没提交上来

2019-04-19 16:31 UTC, ddddyyyy commented
> main函数的改动不用提交，然后主要改动好像全都没提交上来

请直接看[https://github.com/MewX/cross-channel_chinese-localization_project/pull/3/commits/ca51e633104488cefd4a3618b592203cb366b557](url)
ca51e63这个提交，其他的提交是我手残上传上去的😢

2019-08-20 04:37 UTC, MewX commented
一般来说提交pull request直接新建一个branch，然后只做想要merge 的改动在这个branch，自己的改动可以放在其他branch。

我看了下后面的提交，很多临时文件和输入文件都提交进来了，有点messy，没法merge。

你要不要试试新建一个branch，然后 `git reset --hard ca51e633104488cefd4a3618b592203cb366b557`。如果有其他想要添加进来的就用 `git cherrypick` 加进这个branch。然后提交一个新的pull request？

如果不想练手的话，我可以直接代劳

2019-08-20 04:38 UTC, MewX approved these changes

2026-03-05 20:47 UTC, merged